"""
Constants for GATT Characteristic UUIDs

Taken from https://github.com/ajchellew/zwiftplay/blob/main/zaplibrary/src/main/java/com/che/zap/device/common/ZapBleUuids.kt
"""

def uuidFromShortString(short_string):
    BT_SIG_UUID_PREFIX = "0000"
    BT_SIG_UUID_SUFFIX = "-0000-1000-8000-00805F9B34FB"
    return f"{BT_SIG_UUID_PREFIX}{short_string}{BT_SIG_UUID_SUFFIX}"

GENERIC_ACCESS_SERVICE_UUID = uuidFromShortString("1800")
DEVICE_NAME_CHARACTERISTIC_UUID = uuidFromShortString("2A00") # Zwift Play
APPEARANCE_CHARACTERISTIC_UUID = uuidFromShortString("2A01")
PREFERRED_CONNECTION_PARAMS_CHARACTERISTIC_UUID =  uuidFromShortString("2A04")
CENTRAL_ADDRESS_RESOLUTION_CHARACTERISTIC_UUID =  uuidFromShortString("2AA6")

GENERIC_ATTRIBUTE_SERVICE_UUID = uuidFromShortString("1801")
SERVICE_CHANGED_CHARACTERISTIC_UUID = uuidFromShortString("2A05")

DEVICE_INFORMATION_SERVICE_UUID = uuidFromShortString("180A")
MANUFACTURER_NAME_STRING_CHARACTERISTIC_UUID = uuidFromShortString("2A29")  # Zwift Inc.
SERIAL_NUMBER_STRING_CHARACTERISTIC_UUID = uuidFromShortString("2A25") # 02-1[MAC]
HARDWARE_REVISION_STRING_CHARACTERISTIC_UUID = uuidFromShortString("2A27") # B.0
FIRMWARE_REVISION_STRING_CHARACTERISTIC_UUID = uuidFromShortString("2A26") # 1.1.0

ZWIFT_CUSTOM_SERVICE_UUID = "00000001-19CA-4651-86E5-FA29DCDD09D1"
ZWIFT_ASYNC_CHARACTERISTIC_UUID = "00000002-19CA-4651-86E5-FA29DCDD09D1"
ZWIFT_SYNC_RX_CHARACTERISTIC_UUID = "00000003-19CA-4651-86E5-FA29DCDD09D1"
ZWIFT_SYNC_TX_CHARACTERISTIC_UUID = "00000004-19CA-4651-86E5-FA29DCDD09D1"
ZWIFT_UNKNOWN_6_CHARACTERISTIC_UUID = "00000006-19CA-4651-86E5-FA29DCDD09D1"

BATTERY_SERVICE_UUID = uuidFromShortString("180F")
BATTERY_LEVEL_CHARACTERISTIC_UUID = uuidFromShortString("2A19") # 89

UUID_NAMES = {
    GENERIC_ACCESS_SERVICE_UUID: "GENERIC_ACCESS_SERVICE_UUID",
    DEVICE_NAME_CHARACTERISTIC_UUID: "DEVICE_NAME_CHARACTERISTIC_UUID",
    APPEARANCE_CHARACTERISTIC_UUID: "APPEARANCE_CHARACTERISTIC_UUID",
    PREFERRED_CONNECTION_PARAMS_CHARACTERISTIC_UUID: "PREFERRED_CONNECTION_PARAMS_CHARACTERISTIC_UUID",
    CENTRAL_ADDRESS_RESOLUTION_CHARACTERISTIC_UUID: "CENTRAL_ADDRESS_RESOLUTION_CHARACTERISTIC_UUID",
    GENERIC_ATTRIBUTE_SERVICE_UUID: "GENERIC_ATTRIBUTE_SERVICE_UUID",
    SERVICE_CHANGED_CHARACTERISTIC_UUID: "SERVICE_CHANGED_CHARACTERISTIC_UUID",
    DEVICE_INFORMATION_SERVICE_UUID: "DEVICE_INFORMATION_SERVICE_UUID",
    MANUFACTURER_NAME_STRING_CHARACTERISTIC_UUID: "MANUFACTURER_NAME_STRING_CHARACTERISTIC_UUID",
    SERIAL_NUMBER_STRING_CHARACTERISTIC_UUID: "SERIAL_NUMBER_STRING_CHARACTERISTIC_UUID",
    HARDWARE_REVISION_STRING_CHARACTERISTIC_UUID: "HARDWARE_REVISION_STRING_CHARACTERISTIC_UUID",
    FIRMWARE_REVISION_STRING_CHARACTERISTIC_UUID: "FIRMWARE_REVISION_STRING_CHARACTERISTIC_UUID",
    ZWIFT_CUSTOM_SERVICE_UUID: "ZWIFT_CUSTOM_SERVICE_UUID",
    ZWIFT_ASYNC_CHARACTERISTIC_UUID: "ZWIFT_ASYNC_CHARACTERISTIC_UUID",
    ZWIFT_SYNC_RX_CHARACTERISTIC_UUID: "ZWIFT_SYNC_RX_CHARACTERISTIC_UUID",
    ZWIFT_SYNC_TX_CHARACTERISTIC_UUID: "ZWIFT_SYNC_TX_CHARACTERISTIC_UUID",
    ZWIFT_UNKNOWN_6_CHARACTERISTIC_UUID: "ZWIFT_UNKNOWN_6_CHARACTERISTIC_UUID",
    BATTERY_SERVICE_UUID: "BATTERY_SERVICE_UUID",
    BATTERY_LEVEL_CHARACTERISTIC_UUID: "BATTERY_LEVEL_CHARACTERISTIC_UUID",
}
